### ISSUE TITLE
[Brl.Clipboard] Create X11 clipboard segfaults

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#126]
```BlitzMax
SuperStrict

Framework Brl.Clipboard
Import Brl.StandardIO

'should use default displayName
Local opts:TX11ClipboardOpts = New TX11ClipboardOpts
Local clipboard:TClipboard = New TClipBoard.Create( opts ) 'segfault
```
segfaults (in the c file)

```GDB
#0  0x00007fffffffdaf0 in ?? ()
#1  0x000000000040d7b0 in clipboard_new (cb_opts=cb_opts@entry=0x7fffffffda80)
    at /BlitzMaxNG/mod/brl.mod/clipboard.mod/libclipboard/src/clipboard_x11.c:466
#2  0x000000000040cbea in bmx_clipboard_new_x11 (
    actionTimeout=<optimized out>, transferSize=transferSize@entry=1048576, 
    displayName=displayName@entry=0x6649e0 <bbEmptyString>)
    at /BlitzMaxNG/mod/brl.mod/clipboard.mod/glue.c:39
```

passing `null` as opts param works.
setting `opts.displayName = "NULL"` does not change anything.

Seems as if the default value is not working.

**Comment by woollybah** [comment]
Seems I'm not initialising my structs correctly.
