### ISSUE TITLE
StringMap: segfault

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#134]
I just updated all modules and while some apps (like MaxGUI) work I get a segfault in my project when utilizing the TStringMap.

```GDB
Thread 1 "test.visual.off" received signal SIGSEGV, Segmentation fault.
bbStringCompare (x=0x7fffef4dd060, y=0x10)
    at /BlitzMaxNG/mod/brl.mod/blitz.mod/blitz_string.c:284
284		sz=x->length<y->length ? x->length : y->length;
(gdb) bt
#0  bbStringCompare (x=0x7fffef4dd060, y=0x10)
    at /BlitzMaxNG/mod/brl.mod/blitz.mod/blitz_string.c:284
#1  0x0000000000e9ec09 in tree_map (root=0x7ffff7e59fe8, 
    compare=0xe01960 <compare_stringmap_nodes>, new=0x182b300)
    at /BlitzMaxNG/mod/brl.mod/blitz.mod/tree/tree.c:184
#2  avl_map (new=new@entry=0x182b300, 
    compare=compare@entry=0xe01960 <compare_stringmap_nodes>, 
    root=root@entry=0x7ffff7e59fe8)
    at /BlitzMaxNG/mod/brl.mod/blitz.mod/tree/tree.c:637
#3  0x0000000000e0212a in bmx_map_stringmap_insert (key=0x7fffef4dd060, 
    value=0x7ffff7e4d680, root=0x7ffff7e59fe8)
    at /BlitzMaxNG/mod/brl.mod/map.mod/map.c:291
#4  0x0000000000dfd6fa in _brl_map_stringmap_TStringMap_Insert_STObject (
    o=0x7ffff7e59fe0, bbt_key=0x7fffef4dd060, bbt_value=0x7ffff7e4d680)
```
It of course... worked before.

Any ideas what could be happening here?

**Comment by GWRon** [comment]
Ah ... BCC update solved it.
