### ISSUE TITLE
[Brl.Map] Map or GC: using "C-Maps" leads to stutter

### ISSUE THREAD

**Issue by GWRon** [bmx-ng/brl.mod#258]
```BlitzMax
                    For local count:Int = 1 to 1000
                        Local map:TIntMap = new TIntMap
                        For local pointCount:Int = 0 to 1000
                            map.Insert(pointCount, new TImage)
                        Next
                    Next
```
using this a multiple times made my game stutter on that users computer from then on. It never "calmed down" .

replacing "TIntMap" with "TMap" and using `string(pointCount)` as key - and no stutter happens.

TIntMap and the likes use:
```
void bmx_map_intmap_insert( int key, BBObject *value, struct avl_root ** root ) {
	struct intmap_node * node = (struct intmap_node *)GC_malloc_uncollectable(sizeof(struct intmap_node));
```
GC_malloc_uncollectable defined in blitz.mod/bdwgc/include/gc/gc.h:
```C
/* [...] GC_malloc_uncollectable allocates            */
/* an object that is scanned for pointers to collectible                */
/* objects, but is not itself collectible.  The object is scanned even  */
/* if it does not appear to be reachable.  GC_malloc_uncollectable and  */
/* GC_free called on the resulting object implicitly update             */
/* GC_non_gc_bytes appropriately.               */
```

Dunno if the GC is bugged there ... and does not get rid of "what to scan" or if the TIntMap (and consortes) implementation does not "free" correctly?

**Comment by GWRon** [comment]
Interesting bit: my "new code" segfaults if I have a loop of 10.000.000 instead of 1.000.000:
```
compare_intmap_nodes (x=0x7fffffffdd20, y=0x480026f281058b08)
    at /home/ronny/Arbeit/Tools/BlitzMaxNG/mod/brl.mod/map.mod/map.c:36
36	        return generic_compare(node_x->key, node_y->key);
(gdb) bt
#0  compare_intmap_nodes (x=0x7fffffffdd20, y=0x480026f281058b08) at /home/ronny/Arbeit/Tools/BlitzMaxNG/mod/brl.mod/map.mod/map.c:36
#1  0x0000000000494f5a in tree_search (entry=entry@entry=0x7fffffffdd20, compare=compare@entry=0x437c40 <compare_intmap_nodes>, root=0x480026f281058b08, 
    root@entry=0x7ffff7e3cfd8) at /home/ronny/Arbeit/Tools/BlitzMaxNG/mod/brl.mod/blitz.mod/tree/tree.c:35
#2  0x0000000000437df3 in bmx_map_intmap_insert (key=4215201, value=0x7ffff7e3cfc0, root=0x7ffff7e3cfd8) at /home/ronny/Arbeit/Tools/BlitzMaxNG/mod/brl.mod/map.mod/map.c:74
```

**Comment by GWRon** [comment]
I replaced my code with this:
```C
void bmx_map_intmap_insert( int key, BBObject *value, struct avl_root ** root ) {
	struct avl_root link;
	
	struct intmap_node * old_node = (struct intmap_node *)avl_map(&link, compare_intmap_nodes, root);

	// key already exists. Store the value in this node.
	if (&link != &old_node->link) {
		old_node->value = value;
	// key did not exist. replace node with a managed one
	}else{
		//struct intmap_node * gcmanaged_node = (struct intmap_node *)GC_malloc_explicitly_typed(sizeof(struct intmap_node), maxIntMapDescr);
		struct intmap_node * gcmanaged_node = (struct intmap_node *)GC_malloc_uncollectable(sizeof(struct intmap_node));
		gcmanaged_node->key = key;
		gcmanaged_node->value = value;
		gcmanaged_node->link = link;
	}
}
```

which reduced the benchmark time to 186ms here. Dunno if the code is correct.

**Comment by GWRon** [comment]
Got a handful more reports about that stuttering. So it is less rare than first assumed (especially if you consider how likely you get feedback from users).
All report a "longer game" until it happens - which means more objects in the calculation - and so surely again the 70-80k object creation+deletion amount.


@woollybah Were you somehow able to replicate such an issue or should I try to create a complete "sample app" ? I assume it only stutters if you create a lot of objects for the c-maps, then delete it AND then are "normally" using the GC (so doing your normal app logic stuff).
A simple test application just utilizing the map and a basic "while"-loop with a "frame time chart" probably won't show the stutter.
Maybe even Multithreading has an impact here (if the map is created/used/filled from a thread - dunno how nice the GC plays with threads at all)
